Set minimum node version to 10.22; specify v12 for nvm (#100)
- Using older versions of node can result in this error:

    TypeError: buf.writeBigUInt64BE is not a function

- nvm can automatically use the version specified in .nvmrc. Use node
  version 12 because it is currently recommended for most users